//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OplataTruda
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int idVip { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> idSotr { get; set; }
        public Nullable<double> Summa { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
